/** 我的下载 */
export const MYDOWNLOAD = 'MYDOWNLOAD'
/** 下载清空 */
export const MYDOWNLOAD_RESET = 'MYDOWNLOAD_RESET'
/** 下载详情 */
export const MYDOWNLOAD_DETAIL = 'MYDOWNLOAD_DETAIL'
/** 下载高度 */
export const MYDOWNLOAD_DETAIL_SCROLL = 'MYDOWNLOAD_DETAIL_SCROLL'
/** 下载清空 */
export const MYDOWNLOAD_DETAIL_RESET = 'MYDOWNLOAD_DETAIL_RESET'
