/** 获取班级习题册 */
export const REMEMBER_CLASS = 'REMEMBER_CLASS'
/** 清除班级习题册 */
export const REMEMBER_CLASS_CLEAR = 'REMEMBER_CLASS_CLEAR'
/** 获取习题册切换科目 */
export const REMEMBER_CLASS_SUBJECT_CHANGE = 'REMEMBER_CLASS_SUBJECT_CHANGE'

/** 获取习题册章节 */
export const REMEMBER_CLASS_CHAPTER = 'REMEMBER_CLASS_CHAPTER'
/** 清除章节数据 */
export const REMEMBER_CLASS_CHAPTER_CLEAR = 'REMEMBER_CLASS_CHAPTER_CLEAR'
/** 设置章节高度 */
export const REMEMBER_CLASS_CHAPTER_SCROLL = 'REMEMBER_CLASS_CHAPTER_SCROLL'

/** 获取习题册页码 */
export const REMEMBER_CLASS_PAGE = 'REMEMBER_CLASS_PAGE'
/** 清除习题册页码数据 */
export const REMEMBER_CLASS_PAGE_CLEAR = 'REMEMBER_CLASS_PAGE_CLEAR'
/** 设置习题册页码高度 */
export const REMEMBER_CLASS_PAGE_SCROLL = 'REMEMBER_CLASS_PAGE_SCROLL'

/** 获取练习题 */
export const REMEMBER_CLASS_EXERCISE= 'REMEMBER_CLASS_EXERCISE'
/** 清空练习题 */
export const REMEMBER_CLASS_EXERCISE_CLEAR = 'REMEMBER_CLASS_EXERCISE_CLEAR'
