/** 获取班级习题册 */
export const WORKBOOK_CLASS = 'WORKBOOK_CLASS'
/** 清除班级习题册 */
export const WORKBOOK_CLASS_CLEAR = 'WORKBOOK_CLASS_CLEAR'
/** 获取习题册切换科目 */
export const WORKBOOK_CLASS_SUBJECT_CHANGE = 'WORKBOOK_CLASS_SUBJECT_CHANGE'

/** 获取习题册章节 */
export const WORKBOOK_CLASS_CHAPTER = 'WORKBOOK_CLASS_CHAPTER'
/** 清除章节数据 */
export const WORKBOOK_CLASS_CHAPTER_CLEAR = 'WORKBOOK_CLASS_CHAPTER_CLEAR'
/** 设置章节高度 */
export const WORKBOOK_CLASS_CHAPTER_SCROLL = 'WORKBOOK_CLASS_CHAPTER_SCROLL'
/**获取班级所有教材 */
export const WORKBOOK_CLASS_TEXTBOOK = 'WORKBOOK_CLASS_TEXTBOOK'

/** 获取练习题 */
export const WORKBOOK_CLASS_EXERCISE= 'WORKBOOK_CLASS_EXERCISE'
/** 本章练习题已阅 */
export const WORKBOOK_CLASS_EXERCISE_READ= 'WORKBOOK_CLASS_EXERCISE_READ'
/**获取班级练习照片 */
export const WORKBOOK_CLASS_EXERCISE_ANSWER = 'WORKBOOK_CLASS_EXERCISE_ANSWER'
/** 清空练习题 */
export const WORKBOOK_CLASS_EXERCISE_CLEAR = 'WORKBOOK_CLASS_EXERCISE_CLEAR'
