/*短信注册账号*/
export const GET_REGISTER_MESSAGE_SUCCESS = 'GET_REGISTER_MESSAGE_SUCCESS'
/*设置密码*/
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS'
/*登陆*/
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
/*短信重置账号密码*/
export const GET_FORGET_MESSAGE_SUCCESS = 'GET_FORGET_MESSAGE_SUCCESS'
/*重置密码*/
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
/*设置头像*/
export const SET_HEAD_IMG = 'SET_HEAD_IMG'
