/*获取归纳本列表ID*/
export const GET_ERROR_INDEXIDS_SUCCESS = 'GET_ERROR_INDEXIDS_SUCCESS'
export const GET_ERROR_INDEXIDS_ERROR = 'GET_ERROR_INDEXIDS_ERROR'
export const GET_ERROR_INDEXLIST_SUCCESS = 'GET_ERROR_INDEXLIST_SUCCESS'
export const GET_ERROR_INDEXLIST_ERROR = 'GET_ERROR_INDEXLIST_ERROR'

// /*获取归纳本错题列表ID*/
export const GET_ERROR_LISTIDS_SUCCESS = 'GET_ERROR_LISTIDS_SUCCESS'
export const GET_ERROR_LISTIDS_ERROR = 'GET_ERROR_LISTIDS_ERROR'
export const GET_ERROR_LISTLIST_SUCCESS = 'GET_ERROR_LISTLIST_SUCCESS'
export const GET_ERROR_LISTLIST_ERROR = 'GET_ERROR_LISTLIST_ERROR'

export const SET_KNOWLEDGE_ID = 'SET_KNOWLEDGE_ID'

export const CLEAR_LIST = 'CLEAR_LIST'
