/** 按照学生排序*/
export const GET_ERROR_INDEXIDS = 'GET_ERROR_INDEXIDS'
export const GET_ERROR_INDEXLIST = 'GET_ERROR_INDEXLIST'
export const ERROR_STUD_SUBJECT_CHANGE = 'ERROR_STUD_SUBJECT_CHANGE'
export const ERROR_STUD_RELOAD = 'ERROR_STUD_RELOAD'
export const ERROR_STUD_TAB_CHANGE = 'ERROR_STUD_TAB_CHANGE'
export const ERROR_STUD_SCOLL = 'ERROR_STUD_SCOLL'
